# Generated by Django 3.1.3 on 2021-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.TextField(max_length=30)),
                ('desc', models.TextField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('songs', models.FileField(upload_to='music/')),
                ('artist', models.TextField(max_length=30)),
            ],
        ),
    ]
